# See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images faster for debugging.

# Base runtime image
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

# Build and publish
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS publish
WORKDIR /src

# Copy entire repo to ensure custom MSBuild imports (msbuildLib) are available
# .dockerignore causes not all the files are copied.
COPY . .

# Restore and publish
RUN dotnet restore "Projects/RmqToRestApiForwarder/RmqToRestApiForwarder.csproj"
WORKDIR /src/Projects/RmqToRestApiForwarder
RUN dotnet publish "RmqToRestApiForwarder.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Final image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "RmqToRestApiForwarder.dll"]
